title: Saksham Jain # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Software Engineer I 
  <br><br>
  Seeking a challenging position and strive for excellence with dedication, proactive approach, positive attitude and passion towards the work that will fully utilize my logical and reasoning abilities in the best possible way for the fulfilment of organizational goals. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
