title: Saksham Jain
logo: "/images/pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Seeking a challenging position and strive for excellence with dedication, proactive approach, positive attitude and passion towards the work that will fully utilize my logical and reasoning abilities in the best possible way for the fulfillment of organizational goals.
 <br><br>
  <br><br><br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/saksham-jain-2204/">View My LinkedIn Profile</a> 
